version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - travellist

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - travellist

  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - travellist

networks: 
  travellist:
    driver: bridge

volumes:
  db_data:
